import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google"
import "./globals.css"
import { HydrationOverlay } from "@builder.io/react-hydration-overlay"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Rohit K F",
  description: "Portfolio website generated by Rohit K F",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <HydrationOverlay>
          {children}
          <SpeedInsights />
          <Analytics />
        </HydrationOverlay>
      </body>
    </html>
  )
}
