import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google"
import "./globals.css"
import { HydrationOverlay } from "@builder.io/react-hydration-overlay"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Rohit K F",
  description: "Portfolio website generated by Rohit K F",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </head>
      <body className={inter.className}>
        <HydrationOverlay>
          {children}
          <SpeedInsights />
          <Analytics />
        </HydrationOverlay>
      </body>
    </html>
  )
}
