/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fJuhhpcvSma
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardContent, Card, CardDescription } from "@/components/ui/card"

export function Nav() {
  return (
    (<div className="bg-[#121212] text-white">
      <header
        className="flex justify-between items-center p-4 border-b border-gray-700">
        <div className="flex items-center space-x-4">
          <FlagIcon className="text-yellow-500 text-3xl" />
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link className="hover:text-yellow-500" href="#">
                  About
                </Link>
              </li>
              <li>
                <Link className="hover:text-yellow-500" href="#">
                  Portfolio
                </Link>
              </li>
              <li>
                <Link className="hover:text-yellow-500" href="#">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </div>
        <div className="flex items-center space-x-2">
          <Input
            className="rounded bg-gray-800 text-white"
            placeholder="Search"
            type="search" />
          <Button className="bg-yellow-500 hover:bg-yellow-600 text-black">Search</Button>
        </div>
      </header>
      <section className="text-center py-12">
        <Avatar className="mx-auto mb-4">
          <AvatarImage alt="Ivan Dan" src="/placeholder.svg?height=128&width=128" />
        </Avatar>
        <h1 className="text-4xl font-bold">I'M Ivan Dan</h1>
        <p className="text-xl my-2">Python Developer & ERPNext Consultant</p>
        <Button className="mt-4 bg-yellow-500 hover:bg-yellow-600 text-black">Contact Me</Button>
        <div className="flex justify-center space-x-4 mt-4">
          <LinkedinIcon className="text-gray-400 hover:text-yellow-500" />
          <TwitterIcon className="text-gray-400 hover:text-yellow-500" />
          <GithubIcon className="text-gray-400 hover:text-yellow-500" />
        </div>
      </section>
      <section className="py-12 px-4" id="about">
        <h2 className="text-3xl font-bold mb-4">About</h2>
        <p className="leading-relaxed mb-4">
          I have acquired and sharpened my skills through years of experience in the field. My expertise lies in Python
          development and ERPNext consulting, where I strive to deliver robust solutions that drive business growth. I
          am committed to continuous learning and staying ahead of industry trends to provide the most efficient and
          innovative solutions.
        </p>
      </section>
      <section className="py-12 px-4" id="skills">
        <h2 className="text-3xl font-bold mb-4">My Skills</h2>
        <div className="grid grid-cols-4 gap-4">
          <Card className="bg-gray-800">
            <CardContent>
              <PiIcon className="text-yellow-500" />
              <CardTitle>Python</CardTitle>
            </CardContent>
          </Card>
        </div>
        <div className="flex justify-center mt-4">
          <DotIcon className="text-gray-600" />
        </div>
      </section>
      <section className="py-12 px-4" id="portfolio">
        <h2 className="text-3xl font-bold mb-4">Portfolio</h2>
        <div className="grid grid-cols-3 gap-4">
          <Card className="bg-gray-800">
            <CardContent>
              <img
                alt="Project image"
                className="mb-4"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <CardTitle>Amazon Scrapper</CardTitle>
              <CardDescription>A powerful tool to extract product data from Amazon.</CardDescription>
            </CardContent>
          </Card>
        </div>
        <Button className="mt-4 bg-yellow-500 hover:bg-yellow-600 text-black">View More</Button>
      </section>
      <section className="py-12 px-4" id="experience">
        <h2 className="text-3xl font-bold mb-4">Experience</h2>
        <div className="space-y-8">
          <div>
            <h3 className="text-xl font-bold">2021 - Senior Python Developer</h3>
            <p className="text-gray-400">Scotech, Toledo</p>
            <p className="mt-2">
              As a Senior Python Developer at Scotech, I led a team of engineers in developing advanced software
              solutions. My role involved architecting systems, writing clean and efficient code, and mentoring junior
              developers to help them grow their skills.
            </p>
          </div>
        </div>
      </section>
      <section className="py-12 px-4 bg-gray-800 text-center" id="testimonial">
        <Avatar className="mx-auto mb-4">
          <AvatarImage alt="Josef Sharon" src="/placeholder.svg?height=128&width=128" />
        </Avatar>
        <blockquote className="italic">
          "The design quality, flexibility, documentation and support are all absolutely excellent. I love the Avoado
          theme for all my clients, knowing that whatever they require, Avoado will be able to deliver."
        </blockquote>
        <p className="mt-4 font-bold">Josef Sharon — CEO, Omsoft</p>
      </section>
      <section className="py-12 px-4" id="contact">
        <h2 className="text-3xl font-bold mb-4">Contact Me</h2>
        <div className="flex justify-center space-x-4">
          <Link className="hover:text-yellow-500" href="#">
            <MailIcon className="mr-2" />
            ivandan@email.com
          </Link>
          <Link className="hover:text-yellow-500" href="#">
            <PhoneIcon className="mr-2" />
            (201) 555-0124
          </Link>
        </div>
        <p className="text-center mt-4">Toledo, United States</p>
        <div className="flex justify-center space-x-4 mt-4">
          <LinkedinIcon className="text-gray-400 hover:text-yellow-500" />
          <TwitterIcon className="text-gray-400 hover:text-yellow-500" />
          <GithubIcon className="text-gray-400 hover:text-yellow-500" />
        </div>
      </section>
      <footer className="py-4 text-center">
        <p>"Thanks for Scrolling"</p>
      </footer>
    </div>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function GithubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>)
  );
}


function PiIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="9" x2="9" y1="4" y2="20" />
      <path d="M4 7c0-1.7 1.3-3 3-3h13" />
      <path d="M18 20c-1.7 0-3-1.3-3-3V4" />
    </svg>)
  );
}


function DotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12.1" cy="12.1" r="1" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}
