/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fJuhhpcvSma
 */
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import { CardTitle, CardContent, Card, CardDescription } from "@/components/ui/card";

export function Nav() {
  return (
    <div className="bg-[#121212] text-white">
      <header className="flex justify-between items-center p-4 border-b border-gray-700">
        <div className="flex items-center space-x-4">
          <FlagIcon className="text-yellow-500 text-3xl" />
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="#" className="hover:text-yellow-500">
                  About
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-yellow-500">
                  Portfolio
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-yellow-500">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </div>
        <div className="flex items-center space-x-2">
          <Input
            className="rounded bg-gray-800 text-white"
            placeholder="Search"
            type="search"
          />
          <Button className="bg-yellow-500 hover:bg-yellow-600 text-black">Search</Button>
        </div>
      </header>
      <section className="text-center py-12">
        <Avatar className="mx-auto mb-4">
          <AvatarImage alt="Ivan Dan" src="/placeholder.svg?height=128&width=128" />
        </Avatar>
        <h1 className="text-4xl font-bold">I'M Ivan Dan</h1>
        <p className="text-xl my-2">Python Developer & ERPNext Consultant</p>
        <Button className="mt-4 bg-yellow-500 hover:bg-yellow-600 text-black">Contact Me</Button>
        <div className="flex justify-center space-x-4 mt-4">
          <LinkedinIcon className="text-gray-400 hover:text-yellow-500" />
          <TwitterIcon className="text-gray-400 hover:text-yellow-500" />
          <GithubIcon className="text-gray-400 hover:text-yellow-500" />
        </div>
      </section>
      <section className="py-12 px-4" id="about">
        <h2 className="text-3xl font-bold mb-4">About</h2>
        <p className="leading-relaxed mb-4">
          I have acquired and sharpened my skills through years of experience in the field. My expertise lies in Python
          development and ERPNext consulting, where I strive to deliver robust solutions that drive business growth. I
          am committed to continuous learning and staying ahead of industry trends to provide the most efficient and
          innovative solutions.
        </p>
      </section>
      <section className="py-12 px-4" id="skills">
        <h2 className="text-3xl font-bold mb-4">My Skills</h2>
        <div className="grid grid-cols-4 gap-4">
          <Card className="bg-gray-800">
            <CardContent>
              <PiIcon className="text-yellow-500" />
              <CardTitle>Python</CardTitle>
            </CardContent>
          </Card>
        </div>
        <div className="flex justify-center mt-4">
          <DotIcon className="text-gray-600" />
        </div>
      </section>
      <section className="py-12 px-4" id="portfolio">
        <h2 className="text-3xl font-bold mb-4">Portfolio</h2>
        <div className="grid grid-cols-3 gap-4">
          <Card className="bg-gray-800">
            <CardContent>
              <img
                alt="Project image"
                className="mb-4"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardTitle>Amazon Scrapper</CardTitle>
              <CardDescription>A powerful tool to extract product data from Amazon.</CardDescription>
            </CardContent>
          </Card>
        </div>
        <Button className="mt-4 bg-yellow-500 hover:bg-yellow-600 text-black">View More</Button>
      </section>
      <section className="py-12 px-4" id="experience">
        <h2 className="text-3xl font-bold mb-4">Experience</h2>
        <div className="space-y-8">
          <div>
            <h3 className="text-xl font-bold">2021 - Senior Python Developer</h3>
            <p className="text-gray-400">Scotech, Toledo</p>
            <p className="mt-2">
              As a Senior Python Developer at Scotech, I led a team of engineers in developing advanced software
              solutions. My role involved architecting systems, writing clean and efficient code, and mentoring junior
              developers to help them grow their skills.
            </p>
          </div>
        </div>
      </section>
      <section className="py-12 px-4 bg-gray-800 text-center" id="testimonial">
        <Avatar className="mx-auto mb-4">
          <AvatarImage alt="Josef Sharon" src="/placeholder.svg?height=128&width=128" />
        </Avatar>
        <blockquote className="italic">
          "The design quality, flexibility, documentation and support are all absolutely excellent. I love the Avoado
          theme for all my clients, knowing that whatever they require, Avoado will be able to deliver."
        </blockquote>
        <p className="mt-4 font-bold">Josef Sharon — CEO, Omsoft</p>
      </section>
      <section className="py-12 px-4" id="contact">
        <h2 className="text-3xl font-bold mb-4">Contact Me</h2>
        <div className="flex justify-center space-x-4">
          <Link href="#" className="hover:text-yellow-500">
            <MailIcon className="mr-2" />
            ivandan@email.com
          </Link>
          <Link href="#" className="hover:text-yellow-500">
            <PhoneIcon className="mr-2" />
            (201) 555-0124
          </Link>
        </div>
        <p className="text-center mt-4">Toledo, United States</p>
        <div className="flex justify-center space-x-4 mt-4">
          <LinkedinIcon className="text-gray-400 hover:text-yellow-500" />
          <TwitterIcon className="text-gray-400 hover:text-yellow-500" />
          <GithubIcon className="text-gray-400 hover:text-yellow-500" />
        </div>
      </section>
      <footer className="py-4 text-center">
        <p>"Thanks for Scrolling"</p>
      </footer>
    </div>
  );
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

// Rest of the icon components remain unchanged

export default Nav;

